class IdxMarket
  # WATCHLIST: polled frequently (every 15 min) for live signals on LQ45+
  WATCHLIST = %w[
    BBCA.JK BBRI.JK BMRI.JK BBNI.JK BRIS.JK
    TLKM.JK ISAT.JK EXCL.JK
    ASII.JK UNVR.JK ICBP.JK INDF.JK MYOR.JK
    KLBF.JK SIDO.JK
    GGRM.JK HMSP.JK
    SMGR.JK INTP.JK
    ANTM.JK INCO.JK MDKA.JK TINS.JK ADRO.JK PTBA.JK ITMG.JK
    UNTR.JK AKRA.JK
    CPIN.JK JPFA.JK
    BUKA.JK GOTO.JK EMTK.JK
    PGAS.JK MEDC.JK
    TPIA.JK BRPT.JK
    ACES.JK MAPI.JK ERAA.JK
    AMRT.JK
    BSDE.JK PWON.JK CTRA.JK
    JSMR.JK
  ].freeze

  # EXTENDED_WATCHLIST: scanned once daily after market close.
  # Approximates KOMPAS100 + IDX30 + popular growth stocks (~150 tickers).
  EXTENDED_WATCHLIST = (WATCHLIST + %w[
    AGRO.JK AMAR.JK ARTO.JK BABP.JK BACA.JK BANK.JK BBHI.JK BBKP.JK BBMD.JK
    BBYB.JK BCIC.JK BDMN.JK BGTG.JK BJBR.JK BJTM.JK BKSW.JK BMAS.JK BNGA.JK
    BNII.JK BNLI.JK BSIM.JK BTPN.JK BTPS.JK BVIC.JK MEGA.JK NISP.JK PNBN.JK
    SDRA.JK
    LSIP.JK SIMP.JK SSMS.JK AALI.JK BWPT.JK DSNG.JK GZCO.JK LUCK.JK SGRO.JK SMAR.JK
    BIRD.JK BLTZ.JK BUVA.JK CMNP.JK GIAA.JK PJAA.JK SMDR.JK TAXI.JK WIIM.JK
    DOID.JK HRUM.JK ELSA.JK ENRG.JK INDY.JK RUIS.JK
    BAJA.JK BTON.JK CAKK.JK CTBN.JK GDST.JK ISSP.JK JKSW.JK KRAS.JK LION.JK
    LMSH.JK NIKL.JK PICO.JK TBMS.JK TIRT.JK
    ADHI.JK NRCA.JK PTPP.JK SSIA.JK TOTL.JK WIKA.JK WSKT.JK
    APLN.JK ASRI.JK BAPA.JK BCIP.JK BEST.JK BIPP.JK BIKA.JK BKDP.JK BKSL.JK
    BMSR.JK COWL.JK CPRO.JK DART.JK DILD.JK DUTI.JK ELTY.JK FMII.JK FORZ.JK
    GAMA.JK GMTD.JK GPRA.JK GWSA.JK JRPT.JK KIJA.JK KPIG.JK LCGP.JK LPCK.JK
    LPKR.JK MDLN.JK MTLA.JK MTSM.JK NIRO.JK OMRE.JK PLIN.JK PUDP.JK PURI.JK
    RBMS.JK RDTX.JK RODA.JK SCBD.JK SMDM.JK SMRA.JK SSIA.JK TARA.JK
    HMSP.JK RMBA.JK ITIC.JK
    AISA.JK ALTO.JK BUDI.JK CEKA.JK CLEO.JK DLTA.JK DMND.JK FOOD.JK HOKI.JK
    KEJU.JK MGNA.JK MLBI.JK PANI.JK PCAR.JK PSDN.JK ROTI.JK SKBM.JK SKLT.JK
    STTP.JK ULTJ.JK
    BTEK.JK DCII.JK DIVA.JK ENVY.JK GLVA.JK KIOS.JK LUCY.JK MCAS.JK MLPT.JK
    MTDL.JK NFCX.JK SKYB.JK ZBRA.JK
    BBLD.JK CFIN.JK CSAP.JK DEFI.JK HDFA.JK MFIN.JK TIFA.JK TRUS.JK VRNA.JK
    CARS.JK
    PRDA.JK SAME.JK SILO.JK SRAJ.JK MIKA.JK HEAL.JK
    JTPE.JK KICI.JK KONI.JK LAPD.JK LMPI.JK PEHA.JK SOHO.JK MERK.JK INAF.JK PYFA.JK
  ]).uniq.freeze

  TZ = "Asia/Jakarta".freeze

  def self.open_now?
    now = Time.current.in_time_zone(TZ)
    return false if now.saturday? || now.sunday?

    minute_of_day = now.hour * 60 + now.min

    if now.friday?
      morning   = (9 * 60)...(11 * 60 + 30)
      afternoon = (14 * 60)...(15 * 60 + 50)
    else
      morning   = (9 * 60)...(12 * 60)
      afternoon = (13 * 60 + 30)...(15 * 60 + 50)
    end

    morning.include?(minute_of_day) || afternoon.include?(minute_of_day)
  end
end
